name: RabbitMQ Integration Build
run-name: "Event: Tag ${{ github.event.client_payload.tag }} from ${{ github.event.client_payload.repo }} MANAGMENT_IMAGE ${{ github.event.client_payload.management_image }} #${{ github.run_number }}"

permissions:
  contents: read
  actions: read

on:
  repository_dispatch:
    types: [integration-rabbit-built]
  workflow_dispatch:

env:
  EVENT_TAG: ${{ github.event.client_payload.tag }}
  EVENT_RABBITMQ_TAG: ${{ github.event.client_payload.rabbitmqTag }}
  EVENT_BASE_IMAGE: ${{ github.event.client_payload.base_image }}
  EVENT_MANAGMENT_IMAGE: ${{ github.event.client_payload.management_image }}
  EVENT_OWNER: ${{ github.event.client_payload.owner }}
  EVENT_REPO: ${{ github.event.client_payload.repo }}
  EVENT_TARGET_BRANCH: ${{ github.event.client_payload.target_branch }}
  EVENT_FORCE_CREATE: ${{ github.event.client_payload.force_create }}
  TECH_BRANCH: feature/integration-build

concurrency:
  # On main/release, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  update-image-reference:
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.load_config.outputs.components }}
      platforms: ${{ steps.load_config.outputs.platforms }}
      tags: ${{ steps.meta.outputs.result }}
      TARGET_BRANCH: ${{ steps.update_tech_branch.outputs.target_branch }}
    permissions:
      contents: write
    steps:
      - name: Check payload
        run: |
          echo "EVENT_TAG=${EVENT_TAG}"
          echo "EVENT_RABBITMQ_TAG=${EVENT_RABBITMQ_TAG}"
          echo "BASE_IMAGE=${EVENT_BASE_IMAGE}"
          echo "MANAGMENT_IMAGE=${EVENT_MANAGMENT_IMAGE}"
          echo "EVENT_OWNER=${EVENT_OWNER}"
          echo "EVENT_REPO=${EVENT_REPO}"
          echo "EVENT_TARGET_BRANCH=${EVENT_TARGET_BRANCH}"
          echo "EVENT_FORCE_CREATE=${EVENT_FORCE_CREATE}"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ env.EVENT_TARGET_BRANCH }}

      - name: Create or update tech branch
        id: update_tech_branch
        env:
          TECH_BRANCH: ${{ env.TECH_BRANCH }}
          TARGET_BRANCH: ${{ env.EVENT_TARGET_BRANCH }}
        run: |
          echo "Tech branch name is: ${TECH_BRANCH}"
          echo "Target branch is: ${TARGET_BRANCH}"
          set -e

          TECH_BRANCH="$TECH_BRANCH"
          TARGET_BRANCH="$TARGET_BRANCH"

          git fetch origin "$TARGET_BRANCH"

          echo "Resetting $TECH_BRANCH to origin/$TARGET_BRANCH"

          git checkout -B "$TECH_BRANCH" "origin/$TARGET_BRANCH"
          git push origin "$TECH_BRANCH" --force
          echo "target_branch=$TECH_BRANCH" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ env.TECH_BRANCH }}
          fetch-depth: 0

      - name: Load Config
        id: load_config
        run: |
          echo "components=$(jq -c '.components' .qubership/docker-build-config.cfg)" >> "$GITHUB_OUTPUT"
          echo "platforms=$(jq -c '.platforms' .qubership/docker-build-config.cfg)" >> "$GITHUB_OUTPUT"
          echo components=$components
          echo platforms=$platforms

      - name: Create Meta info (tags)
        uses: netcracker/qubership-workflow-hub/actions/metadata-action@8d542a426ce561c7dce745f6b9cee068d1d7e101 #v2.0.10
        id: meta
        with:
          ref: ${{ env.TECH_BRANCH }}
          default-template: "{{ref-name}}"
          extra-tags: ${{ env.EVENT_TAG }}
          replace-symbol: "_"

  multiplatform_build:
    name: Build Docker Images
    needs: update-image-reference
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.update-image-reference.outputs.components) }}
    steps:
      - name: Debug tags and components
        run: |
          echo "Tags: ${{ needs.update-image-reference.outputs.tags }}"
          echo "Component: ${{ toJson(matrix.component) }}"
      - name: Set build-args RabbitMQ 3
        if: ${{ matrix.component.name == 'qubership-rabbitmq-image-3' && startsWith(env.EVENT_RABBITMQ_TAG, 'v3') }}
        run: |
          echo "build_args=BASE_IMAGE=${{ env.EVENT_BASE_IMAGE }}" >> $GITHUB_ENV
      - name: Set build-args RabbitMQ 4
        if: ${{ matrix.component.name == 'qubership-rabbitmq-image' && startsWith(env.EVENT_RABBITMQ_TAG, 'v4') }}
        run: |
          echo "build_args=BASE_IMAGE=${{ env.EVENT_BASE_IMAGE }}" >> $GITHUB_ENV
      - name: Docker
        uses: netcracker/qubership-workflow-hub/actions/docker-action@8d542a426ce561c7dce745f6b9cee068d1d7e101 #v2.0.10
        with:
          ref: ${{ env.TECH_BRANCH }}
          component: ${{ toJson(matrix.component) }}
          download-artifact: false
          platforms: ${{ needs.update-image-reference.outputs.platforms }}
          tags: ${{ needs.update-image-reference.outputs.tags }}
          build-args: |
            ${{ env.build_args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

  rabbit-mq-pipeline:
    needs: [update-image-reference, multiplatform_build]
    uses: Netcracker/qubership-test-pipelines/.github/workflows/rabbitmq.yaml@4487afa083e5ba0cf64690d2e93e3d8ee94fab4f # v1.3.0
    with:
      service_branch: "${{ needs.update-image-reference.outputs.TARGET_BRANCH }}"
      versions_file: ".github/versions.yaml"
      pipeline_branch: "4487afa083e5ba0cf64690d2e93e3d8ee94fab4f" #this value must match the value after '@' in 'uses'
    secrets:
      AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
      AWS_S3_ACCESS_KEY_SECRET: ${{ secrets.AWS_S3_ACCESS_KEY_SECRET }}
